config/routes.rb
Rails.application.routes.draw do
  get 'about_us',to: "company#about_us"
  resources :inquiries
  get 'invest', to: "inquiries#invest"
  get 'ourjobs',to: "inquiries#ourjobs"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'job_search', to: "search#job_search"
  get 'search/search', as: :search
  
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :registrations => "registrations" } #新建registrations controller,为了能够注册后重定向到after_signup_path
  scope '(:locale)' do #:locale是插入语，放在path前面，代表了地址里面出现的:locale参数如(en,cn等),
    get 'my_line_items',to:'home#my_line_items'
    get 'my_talents',to:'home#my_talents'
    get 'my_jobs',to:'home#my_jobs'
    
    get 'users/:id/refer', to:'users#refer', as: :user_refer # 简历上点击推荐按钮
    
    devise_scope :user do
      get "sign_out", to: "devise/sessions#destroy"
      get "sign_in", to: "devise/sessions#new"
      get "sign_up", to: "registrations#new"
      end
    root 'front#show'
      
    resources :jobs do
      get 'apply' => :apply
      get 'accept' => 'line_items#accept', as: :accept
      resources :comments
      resources :line_items do
      end
      resources :build, controller: 'jobs/build'
    end
    resources :after_signup
    resources :users do
      get "editsalary", to: "users#editsalary"
      resources :summaries
      resources :educations
      resources :works
      resources :reviews do #因为需要params[:user_id],所以把路径包含resources :users
        member { post :rating }
	get 'reviews/edit' => :edit
      end
    end
  end # end scope '(:locale)'

end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :bosses, :dependent => :destroy
  has_many :subordinates, :dependent => :destroy
  has_many :experiences, :dependent => :destroy
  has_many :line_items
  has_many :comments
  belongs_to:user # 发布者
  has_many :users, through: :line_items
  accepts_nested_attributes_for :bosses,:subordinates,:line_items, :comments, allow_destroy: true
  accepts_nested_attributes_for :experiences,allow_destroy: true,reject_if: proc { |attributes| attributes[:skill].blank? }
  letsrate_rateable "job_rating"
  letsrate_rateable "feedback"
end

app/controllers/jobs/build_controller.rb
class Jobs::BuildController < ApplicationController
  include Wicked::Wizard
  before_action :set_job
  steps :job_scope, :team, :package
  def show

    render_wizard
  end
  
  def update
    @job.update_attributes(job_params)
    @job.user_id = current_user.id
    render_wizard @job
  end
 
  def finish_wizard_path
    job_path(@job)
  end

  private
  def set_job
      @job = Job.find(params[:job_id])
  end

  def job_params
    params.require(:job).permit(
        :title, :addr, :city, :industry, :commission, 
	:role, :requirement, :work_year,
	:base_pay, :month, :bonus, :allowance, :stock, :stock_num, :concall_date,
   	experiences_attributes:[:skill,:year,:_destroy],
   	bosses_attributes: [:title, :job_id,:_destroy],
	subordinates_attributes: [:job_id,:title,:num, :_destroy],
	experiences_attributes: [:skill,:year,:_destroy]
    )
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all.page(params[:page]).per(10) # params[:page]不用设置
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @poster=User.find(@job.user_id) #发布者id
    #session[:talent_id]=nil
    @talent=nil
    @line_item = LineItem.new # form_for @line_item要用
    @line_items = LineItem.where("job_id = ?",@job.id).take(100) #加unless @line_items == nil是错误的，赋值之前永远为nil
    if current_user != nil
      #如果有评论且是登录者的就赋给@comment,否则新建一个
      @comment = @job.comments.present? ? (@job.comments.find_by(user_id:current_user.id) or Comment.new) : Comment.new
     else
       @comment = Comment.new 
     end
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
	format.html { redirect_to job_build_path(job_id: @job.id, id: :job_scope) }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

 def apply
   @job = Job.find(params[:job_id])
   
   respond_to do |format|
      format.html { } # 此处用render partial,则bootstrap javastript不能用，所以用与action同名view的好处就在这里
      format.js
      format.json { render partial: 'apply', status: :created, location: @job }
    end
  end
  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :addr, :city, :industry, :commission, :role, :requirement, :base_pay, :month, :bonus, :allowance, :stock, :stock_num, :concall_date, :user_id, :peer, :memo, :company_info, :work_year)
    end
end

app/helpers/jobs/build_helper.rb
module Jobs::BuildHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_apply.html.erb
<% if can? :read, LineItem %>

    <table class='table table-striped'>
      <% @job.line_items.each do |line_item| %>
        <% if line_item.talent_id !=nil %>
          <tr>
    	<td width='70px'>
              <% @talent=User.find(line_item.talent_id) %>
    	  <% if line_item.status.present? %>
    	    <button class='status-flag'><%= link_to line_item.status %></button>
    	  <% end %>
            </td>
    	<td width='50px'>
    	  <%= link_to image_tag(@talent.avatar.url,size:'30x30'), id: "#{line_item.talent_id}", action: 'show', controller: 'users', host:'localhost:3000'  %>
    	</td>
    	<td>
     	  <%= remove_unwanted_words distance_of_time_in_words(Date.today,@talent.birthday) unless @talent.birthday == nil%> | <%= @talent.educations.first.school unless @talent.educations.first == nil %> | <% @talent.works.each do |f| %>
              <% if f != @talent.works.last %>
    	    <%= f.employer %> | <!-- |不能放在<% %>里-->
              <% else %>
                <%= f.employer %>
              <% end %>
              <% end %>
            </td> 
          </tr>
      <% end %>
      <% end %>
    </table>
<% else %>
  对不起，您没有权限
<% end %>

app/views/jobs/_comment.html.erb
<% @job.comments.order('top desc,created_at desc').each do |comment| %>
  <% if comment.user_id != nil %>
    <table>
      <tr>
	<td><!--tr如果不加td的话下一个tr不会重启一行-->
          <% @author=User.find(comment.user_id) %>
          <%= @author.user_name %>
          <%= @author.works.last.title.present? ? " #{@author.works.last.title} |" : '找工作中 |' %>
          <%= remove_unwanted_words distance_of_time_in_words(Date.today,@author.birthday) unless @author.birthday == nil %>
        </td>
        <td><%= comment.rating %></td>
      </tr>
      <tr>
        <td id='comment_body'>
          <%= comment.body %>
        </td>
        <td style='border-bottom:1px dashed #dddddd'>有用</td>
      </tr>
    </table>
<% end %>
<% end %>

app/views/jobs/_form.html.erb
<div class="container-fluid"><!--Use .container-fluid for a full width container, spanning the entire width of your viewport.-->
    <section class="container"><!--Use .container for a responsive fixed width container.-->
        <div class="container-page"> 
            <div class="col-md-4"><!--col-md对应的Container width：970px -->

                <%= form_for @job do |f| %>
                  <% if @job.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

                      <ul>
                      <% @job.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>

                  <div class="col-lg-6">
                    <%= f.label :title %><br>
                    <%= f.text_field :title,class: 'form-control' %>
                  </div>
                   <div class="col-lg-6">
                    <%= f.label :city %><br>
                    <%= f.text_field :city,class: 'form-control' %>
                  </div>
                  <div class="col-lg-12">
                    <%= f.label :addr %><br>
                    <%= f.text_field :addr,class: 'form-control' %>
                  </div>
                 
                  <div class="col-lg-6">
                    <%= f.label :industry %><br>
                    <%= f.text_field :industry,class: 'form-control' %>
                  </div>
                  <div class="col-lg-6">
                    <%= f.label :commission %><br>
                    <%= f.number_field :commission,class: 'form-control' %>
                  </div>
                  <div class="col-lg-12 select">
                    <%= f.label :concall_date %><br>
                    <%= f.date_select :concall_date,class: 'form-control' %>
                  </div>
                  <div class="col-lg-12">
                    <%= f.label :备注 %><br>
                    <%= f.text_area :memo,class: 'form-control' %>
                  </div>
                  <div class="col-lg-12">
                    <%= f.label :公司卖点和职位亮点 %><br>
                    <%= f.text_area :company_info,class: 'form-control' %>
                  </div>

                  <!--为了留出和下面按钮的空隔-->
                  <div class="form-group col-lg-3 " >
                  </div>

                  <div class="col-lg-12 ">
                    <%= f.submit "继续",class: "btn btn-success" %>
                  </div>
                <% end %>
            </div>
          </div>
      </section>
</div>

app/views/jobs/apply.html.erb
<!-- 本文件用来显示我的职位的应聘简历列表-->
<div class='container'>
<table style='margin-top:100px'class='table table-triped'>
  <thead>
	  <th></th>
	  <th>候选人</th>
	  <th>状态</th>
	  <th>城市</th>
	  <th>年龄</th>
	  <th>雇主</th>
	  <th>职位</th>
	  <th>学校</th>
	  <th>学历</th>
	  <th>月薪</th>
	  <th>年薪</th>
	  <th>期望薪资</th>
	  <th>手机</th>
	  <th>邮箱</th>
   </thead>
  
   <tbody id='line_item' >
	  <% @job.line_items.order("updated_at desc").each do |f| %>
	    <% talent = User.find(f.talent_id) %>
		<tr class='hover'>
		  <td >
		      
		  <button  class='comment' data-toggle="modal" data-target="#comment_<%=f.id%>">
 服务评价
</button>

<!-- Modal -->
<div class="modal fade" id="comment_<%=f.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">服务评价</h4>
      </div>
      <div class="modal-body">
      	请您对<%= f.user.user_name %>评价<br>
      	<%= rating_for f, "service" %>
        
      	<%= form_tag job_line_item_path(id:f.id,job_id:@job.id),method: :put do |line_item| %>
							        
							        <div class="form-group">
							            <label for="message-text" class="control-label"></label>
							            <%= text_area_tag :comment, nil,placeholder: "输入评语",class: "form-control"  %><!--第一个参数是输入params的id,第二个是输入的内容，因为我们从params[:comment]输入，所以这个为nil,注意如果漏掉，则后面的参数会变成输入的内容而发生错误-->
							        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">放弃</button>
        <%= submit_tag "确认", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
		  
		  
		  </td>
		  <td><%= link_to "#{talent.user_name}",user_path(talent),target:"_blank" %></td>
		  <td >
			<!-- Button trigger modal -->
			<a type="button" data-toggle="modal" data-target="#lineitem_<%=f.id%>">
			  <%= f.status %>
			</a>

			<!-- Modal -->
			<div class="modal fade" id="lineitem_<%=f.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
			<div class="modal-content">
							<div class="modal-header">
						        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						        <h4 class="modal-title">面试进度</h4>
						    </div>
		      				<div class="modal-body">
		      						<%= form_tag job_line_item_path(id:f.id,job_id:@job.id),method: :put do |line_item| %>
							        <div class="form-group">
							            <label for="recipient-name" class="control-label">下一步状态</label>
							              
										<%= select_tag :status,"<option>Reject</option><option>turndown</option><option>发送到line</option><option>等待反馈</option><option>初面</option><option>最后面试</option><option>Offer</option><option>保证期</option><option>推荐成功</option>".html_safe, class: 'form-control' %> <!--这种写法是最保险的，否则会出问题。-->
							        </div>
							        <div class="form-group">
							            <label for="message-text" class="control-label">给推荐者反馈</label>
							            <%= text_area_tag :feedback, nil,class: "form-control"  %><!--第一个参数是输入params的id,第二个是输入的内容，因为我们从params[:comment]输入，所以这个为nil,注意如果漏掉，则后面的参数会变成输入的内容而发生错误-->
							        </div>
							</div>
					        <div class="modal-footer">
								    <button type="button" class="btn btn-default" data-dismiss="modal">放弃</button>
							        <%= submit_tag "确认", class: "btn btn-primary" %>
							        <% end %>	
					        </div>

				      
			</div><!--modal-content-->
			</div>
			</div>
      	  </td>
		  <td><%= talent.city %></td>
		  <td><%= age(talent.birthday) %></td>
		  <% if talent.works.find_by(uptonow: true)  %> <!-- find_by可用作判断, where不用作判断-->
		  <td><%= talent.works.where(uptonow: true).take.employer %></td>
		  <td><%= talent.works.where(uptonow: true).take.title %></td>
		  <% else %>
		  <td><%= talent.works.where(leave_date: talent.works.maximum(:leave_date)).take.employer %></td><!--加take可以用.employer-->
		  <td><%= talent.works.where(leave_date: talent.works.maximum(:leave_date)).take.title %></td><!--加take可以用.employer-->
		  <% end %>
		  <% if talent.educations.find_by(degree: "本科") %>
		  <td><%= talent.educations.where(degree:"本科").take.school %></td>
		  <td><%= "本科" %></td>
		  <% elsif talent.educations.find_by(degree: "硕士") %>
		  <td><%= talent.educations.where(degree:"硕士").take.school %></td>
		  <td><%= "硕士" %></td>
		  <% else %>
		  <td><%= talent.educations.first.school %></td>
		  <td><%= talent.educations.first.degree %></td>
		  <% end %>
		  <td><%= talent.base_salary %></td>
		  <td><%= (talent.base_salary ||=0)*(talent.month_num||=0)+(talent.bonus||=0)+(talent.housing||=0)+(talent.transport||=0)+(talent.retention_bonus||=0) %></td>
		  <td><%= talent.expect_package %></td>
		  <td><%= talent.mobile %></td>
		  <td><%= talent.email %></td>
	        </tr>	
	<% end %>
</tbody>
</table>
</div>

app/views/jobs/apply.js.erb
$('#content').html("<%= escape_javascript(render "apply") %>");

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/new.html.erb
<h1>发布职位</h1>

<%= render 'form' %>

app/views/jobs/show.html.erb
<div style='padding-top:80px' class='container' >
  <div class='row'>
    <%= notice %>
  </div>
  
  <div class='row'>
    <div class='col-lg-6'>
    <p id='title'>
      <table>
        <tr>
          <td><span style='font-size:20px'><%= @job.title %></span></td>
        </tr>
        <tr>
          <td><%= rating_for @job, "job_rating" %></td>
        </tr>
      </table>
    </p>
    </div>
  </div>

  <div class='row'>
    <div class='col-lg-3'>
      <table>
        <tr><td><strong>坐标:</strong></td><td><%= @job.city %> | <%= @job.addr %></td></tr>
        <tr><td><strong>行业:</strong></td><td><%= @job.industry.present? ? @job.industry : '面议' %></td></tr>
	<% if @job.base_pay != 0 %>
	  <tr><td><strong>年薪:</strong></td><td><%= @job.base_pay.present? ? "#{@job.base_pay}人民币 x  #{@job.month}" : '面议' %></td></tr>
        <% end %>
        <tr><td><strong>奖金:</strong></td><td><%= @job.bonus.present? ? "#{@job.bonus} 人民币" : '面议' %></td></tr>
        <tr><td width='60px'><strong>发布时间:</strong></td><td><%= @job.created_at.strftime("%Y-%m-%d") %></td></tr>
        <tr><td><strong>最后回复:</strong></td><td>2014-10-20</td></tr>
        <tr><td><strong>备忘:</strong></td><td><%= @job.memo %></td></tr>
      </table>
    </div><!--cl-lg-3-->
 
    <div class='col-lg-4'>
      <p><span style='font-size:35px;font-family:Georgia;color:#fa6464'><%= @job.commission %></span><span style='font-size:10px;'>现金推荐奖</span></p>
      <p>经验要求:<%= @job.work_year %>年</p>
      <table>
       <% @job.experiences.each do |f| %>
      	 <tr>
        	   <td style='font-size:12px'><%= f.skill %></td>
      	   <td>&nbsp;<% (f.year<=10 ? "#{(f.year+1)/2}" : 5).to_i.times do %>
      	     <span style="margin-left:-3px;border-radius:1px;background-color:#ff632f;color:#ffffff;" class="glyphicon glyphicon-star" aria-hidden="true"></span>
                   <% end %>
           	   </td>
      	   <td style='font-size:10px'>&nbsp;
      	     <%= f.year %>年
      	   </td>
         </tr>
       <% end %>
     </table> 
    </div> 
  </div><!--row-->

  <div><br /></div>
  <div class='row'>
    <div class='col-lg-4' id='orange'>
      <button class='btn-orange'>关注</button>
      <button class='btn-orange'>分享</button>
      <button class='btn-orange'>预约</button>
      <button class='btn-orange'>领取任务</button>
    </div>
   
    <div class='col-lg-4'  >
      <div class='col-lg-2' >
	<button type='button' class='btn btn-xs btn-success' data-toggle="modal" data-target="#myModal">
	   <!-- <%= link_to '推荐',new_job_line_item_path(@job) %>--><!--带上job_id是为了推荐方便-->
		 推荐
  	</button>
	<!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div style='width:400px' class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
		      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		      <h4 class="modal-title" id="myModalLabel">推荐您的朋友或者同事</h4>
	      </div>

	      <div class="modal-body">
              <!-- Modal body content -->
		<%= form_for @line_item, url: job_line_items_path(job_id:@job.id), method: :post do |f| %>
  		  <% if @line_item.errors.any? %>
    		  <div id="error_explanation">
      		  <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>
      			<ul>
      				<% @line_item.errors.full_messages.each do |message| %>
        		        	<li><%= message %></li>
      				<% end %>
      			</ul>
    		  </div>
  		<% end %>
       
		<div class='input-group col-lg-7'>
			<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
			<%= f.text_field :email, class: 'form-control',placeholder:'输入邮箱地址' %>
		</div>
		<br>
		<div class='input-group col-lg-7'>
			<span class="input-group-addon"><i style='width:14px' class="fa fa-mobile"></i></span>
			<%= f.text_field :mobile, class: 'form-control input',placeholder:'输入手机号' %>
		</div>
		<br>
		<div class='input-group col-lg-7'>
			<span class="input-group-addon"><i style='width:14px' class="fa fa-user"></i></span>
			<%= f.text_field :name, class: 'form-control input',placeholder:'对方姓名' %>
		</div>
	
	        </div><!--modal body end -->
              		
  	        <div class="modal-footer">
		      <!--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
		      <%= f.submit "分享",class: 'btn btn-danger' %>
		      </div>
	  	<% end %>	

            </div>
          </div>
        </div>
      </div>

      <div class='col-lg-2'><!-- 与推荐按钮并列-->
	<%= button_to '应聘',job_accept_path(@job),method: :get, class: 'btn btn-success btn-xs' %>
      </div>
      
    </div>
  </div>

  <div><!--divide-->
    <br />  <br />
  </div>

  <div class='row'>
    <div class='col-lg-6'>
      <!--把/n换成回车并且插入段落标记和首行缩进-->
      <p class='text'><%= @job.company_info.gsub(/\n/,'</p><p class="text">').html_safe unless @job.company_info.blank? %></p>
    </div>
 </div> 

  <div class='row'>
    <div class='col-lg-6'>
      <p class='green_title'>工作职责· · · · · ·</p>
      <p class='text'><%= @job.role.gsub(/\n/,'</p><p class="text">').html_safe unless @job.role.blank? %></p>
    </div>
  </div>

  <div><!--divide-->
    <br />
  </div>

  <div class='row'>
    <div class='col-lg-6'>
      <p class='green_title'>职位要求· · · · · ·</p>
      <p class='text'><%= @job.requirement.gsub(/\n/,'</p><p class="text">').html_safe unless @job.requirement.blank? %></p>
    </div>
  </div>

  <div><!--divide-->
    <br />
  </div>

  <div class='row'>
    <div class='col-lg-2'>
      <p class='green_title'>汇报对象:</p>
          <% if @job.bosses != nil %>
	  <% @job.bosses.each do |f| %>
	  <p class='text'><%= f.title %></p><!--text为了段落缩进-->
          <% end %> 
      <% end %>
    </div>
    <div class='col-lg-2'>
      <p class='green_title'>下属:</p>
        <% if @job.subordinates != nil %>
	  <table>
    	    <% @job.subordinates.each do |f| %>
	      <tr>
	        <td><%= f.title %>&nbsp;&nbsp;</td>
		<td><%= f.num %>人</td>
	      </tr>
	        <% end %>
	   </table>
            <% end %>
    </div>
  </div><!--row-->

  <div><!--divide-->
    <br />
  </div>
  
  <div><!--divide-->
    <br />
  </div>

  

  <div class='row'>
    <div role="tabpanel">

      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">评论</a></li>
        <li role="presentation"><a href="#apply" aria-controls="apply" role="tab" data-toggle="tab">申请者</a></li>
        <li role="presentation"><a href="#poster" aria-controls="poster" role="tab" data-toggle="tab">关于招聘者</a></li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <!--评论tab-->
        <div role="tabpanel" class="tab-pane active" id="home">
            <div id="accordion" role="tablist" aria-multiselectable="true">
              <div class='row'>
                  <div class='col-lg-3 list'>
                      <%= link_to "#{@job.comments.count}条评论", job_comments_path(@job),remote:true %>

                  </div>

                  <div class='col-lg-5 list no_underline'>
                     <!--collapse-->
                     <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                   
                              <% if (current_user != nil) and (@job.comments.find_by user_id: current_user.id)  %>
                                <span class='no_underline' id='label-1'>修改点评</span>
                              <% else %>
                                <span id='label-2'>我也说两句</span>
                              <% end %>
                     </a>
                  </div>
              </div><!--row-->

              <div class='row'>
                  <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne" style="margin:0px;">
                    <div class='col-lg-4'>
                      <div class="panel-body">

                            <%= form_for([@job,@comment]) do |f| %>
                            <%= f.text_area :body, placeholder:'请输入评论',class: "form-control" %>
                      </div>
                    </div> 
                    <div class='col-lg-3'>
                      <table>
                        <tr>
                          <td>总体评价</td><td><%= rating_for @job, "job_rating" %></td>
                        </tr>
                        <tr>
                          <td>反馈速度</td><td><%= rating_for @job, "feedback" %></td>
                        </tr>
                      </table>
                    
                      <div >
                        <%= f.submit '发表',class: "btn btn-success" %>
                        <% end %>
                      </div>
                    </div><!--col-lg-->
                  </div>
              </div><!--row-->

            </div><!--accordion-->
            <div class='row'>
              <%= render @job.comments.order('top asc,created_at asc') %> <!--这句话是从views/comments/下面取模板-->
            </div>
          </div>

      <!--应聘者-->
      <div role="tabpanel" class="tab-pane" id="apply">
	<%= render "apply" %>
      </div>
      <!--招聘者界面-->
      <div role="tabpanel" class="tab-pane" id="poster">
        <br>
          <%= image_tag(@poster.avatar.url(:small),class: "img-rounded") %>
        
      </div>


    </div><!-- Tab panes -->

  </div>
</div><!--row-->
</div>