config/routes.rb
Rails.application.routes.draw do
  get 'about_us',to: "company#about_us"
  resources :inquiries
  get 'invest', to: "inquiries#invest"
  get 'ourjobs',to: "inquiries#ourjobs"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'job_search', to: "search#job_search"
  get 'search/search', as: :search
  
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :registrations => "registrations" } #新建registrations controller,为了能够注册后重定向到after_signup_path
  scope '(:locale)' do #:locale是插入语，放在path前面，代表了地址里面出现的:locale参数如(en,cn等),
    get 'my_line_items',to:'home#my_line_items'
    get 'my_talents',to:'home#my_talents'
    get 'my_jobs',to:'home#my_jobs'
    
    get 'users/:id/refer', to:'users#refer', as: :user_refer # 简历上点击推荐按钮
    
    devise_scope :user do
      get "sign_out", to: "devise/sessions#destroy"
      get "sign_in", to: "devise/sessions#new"
      get "sign_up", to: "registrations#new"
      end
    root 'front#show'
      
    resources :jobs do
      get 'apply' => :apply
      get 'accept' => 'line_items#accept', as: :accept
      resources :comments
      resources :line_items do
      end
      resources :build, controller: 'jobs/build'
    end
    resources :after_signup
    resources :users do
      get "editsalary", to: "users#editsalary"
      resources :summaries
      resources :educations
      resources :works
      resources :reviews do #因为需要params[:user_id],所以把路径包含resources :users
        member { post :rating }
	get 'reviews/edit' => :edit
      end
    end
  end # end scope '(:locale)'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  letsrate_rater
  has_many :summaries, :dependent => :destroy
  has_many :educations, :dependent => :destroy
  has_many :works,:dependent => :destroy
  has_many :reviews, :dependent => :destroy
  has_many :line_items

  has_many :jobs # 发布的职位

  accepts_nested_attributes_for :summaries, allow_destroy:true,reject_if: proc { |attributes| attributes['content'].blank? } 
  accepts_nested_attributes_for :educations, allow_destroy:true,reject_if: proc { |attributes| attributes['school'].blank? }
  accepts_nested_attributes_for :works, allow_destroy:true,reject_if: proc { |attributes| attributes['employer'].blank? }# proc的用法http://ruby-doc.org/core-2.1.1/Proc.html
  accepts_nested_attributes_for :line_items
  accepts_nested_attributes_for :reviews
  accepts_nested_attributes_for :jobs

  # avatar设置
  has_attached_file :avatar, :styles => {:medium => "100x100#", :small => "50x50#"}, :default_url => "missing.png"#路径直接对应/app/assets/images/*,不能加其他
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  DEGREE_TYPES = ['专科','专升本','本科','统招硕士','工程硕士','MBA', '博士']


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:refer,:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!,only: [:index,:new,:create] #devise认证user
  layout :determine_layout
  # 推荐候选人页面
  def refer
    session[:talent_id]= params[:id]
    @talent = User.find(session[:talent_id])
    jobs = Job.all # 这个jobs要在循环外定义,否则会不认
    
    # 筛选出候选人没有应聘过的职位
    line_items = LineItem.where(talent_id: session[:talent_id])
    line_items.each do |f|
      jobs = jobs.where.not(id:f.job_id)
    end
    @jobs = jobs.page(params[:page]).per(5)
    render 'refer'  
  end

  
  # GET /users
  # GET /users.json
  def index
    session[:build_sum] = false
    @users = User.all.page(params[:page]).per(10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @total_apply_num = LineItem.where(talent_id: @user.id).size
    @fail_num = LineItem.where(talent_id: @user.id).where(status: "HR拒绝").size

    @offers = @user.line_items.where(status: "offer").sum(:commission)
    if current_user != nil
      @review = @user.reviews.present? ? (@user.reviews.find_by(author_id:current_user.id) or Review.new) : Review.new
    else
      @review = Review.new
    end
    if can? :read, @user
      case @user.user_type
      when "猎头"
        @resume_bank = User.where(bank_id: @user.id)
        render 'hunter'
      when "求职者"
        render 'talent'
      when "人事"
	render "hr"
      end
    else
      redirect_to users_path
    end 
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    respond_to do |format|
      format.html { render :edit }
      format.js 
      end
  end

  def editsalary
    @user = User.find(params[:user_id])
    respond_to do |format|
      format.html { render :edit }
      format.js 
      end
  end
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.js
	format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def determine_layout
      case action_name
      when "show"
        if @user.user_type=="猎头"
	  "application_hunter"
	else
	  "application"
	end
      else
	"application"
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
    params.require(:user).permit(
      :tag_list,
      :avatar,
      :mobile, :user_name, :true_name, :user_type, :email, :birthday,:city,:title,
      :base_salary, :month_num, :bonus, :housing, :transport, :stock,:stock_num, 
      :retention_bonus, :expect_package, :expect_month_salary,
      summaries_attributes: [:user_id, :content, :_destroy],
      educations_attributes: [:user_id, :school, :enter_school, :leave_school,
      :major, :degree, :_destroy],
      works_attributes: [:user_id, :title,:employer,:join_date,:leave_date,:industry, :job_scope, :_destroy]
     )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class='row'>
<h4>自我评价和总结&nbsp;<%= link_to "修改",edit_user_summary_path(user_id: @user), class: "btn-orange", remote:true %></h4>
  <div class='col-lg-10' style='padding-left:20px' id="summary-content">
    <%= render "summary_list" %>
  </div>
</div>
<div class='row'>
<h4>工作经历&nbsp;<%= link_to "修改",edit_user_work_path(user_id: @user), class: "btn-orange", remote:true %></h4>
  <div class='col-lg-10' style='padding-left:20px' id="work-content">
    <%= render "work_list" %>
  </div>
</div>

<div class='row'>
<h4>教育经历&nbsp;<%= link_to "修改",edit_user_education_path(user_id: @user), class: "btn-orange", remote:true %></h4>
  <div class='col-lg-10' style='padding-left:20px' id="education-content">
    <%= render "education_list" %>
  </div>
</div>

<div class='row'>
<h4>薪资状况&nbsp;<%= link_to "修改",user_editsalary_path(user_id: @user), class: "btn-orange", remote:true %></h4>
  <div class='col-lg-10' style='padding-left:20px' id="salary-content">
    <%= render "salary_list" %>
  </div>
</div>

<div class='row basic'>
<h4>基本信息</h4>
  <div class='col-lg-8'>
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>


      <div class='col-lg-6'>
        <li><%= f.label :手机 %></li>
        <li><%= f.text_field :mobile,class: "form-control" %></li>
      </div>

      <div class='col-lg-6'>
        <li><%= f.label :用户名 %></li>
        <li><%= f.text_field :user_name,class: "form-control" %></li>
      </div>

      <div class='col-lg-6'>
        <li><%= f.label :真实姓名 %></li>
        <li><%= f.text_field :true_name,class: "form-control" %></li>
      </div>

      <div class='col-lg-6'>
        <li><%= f.label :用户类型 %></li>
        <li><%= f.text_field :user_type,class: "form-control" %></li>
      </div>

      <div class='col-lg-6'>
        <li><%= f.label :邮箱 %></li>
        <li><%= f.text_field :email,class: "form-control" %></li>
      </div>

      <div class='col-lg-6'>
        <li><%= f.label :生日 %></li>
        <li><%= f.date_select :birthday,class: "form-control" %></li>
      </div>

      <div class='col-lg-6'>
        <li><%= f.label :城市 %></li>
        <li><%= f.text_field :city,class: "form-control" %></li>
      </div>

      <div class='col-lg-6'>
        <li><%= f.label :职衔 %></li>
        <li><%= f.text_field :title,class: "form-control" %></li>
      </div>

      <div class='col-lg-12'>
        <br>
        <%= f.submit "更新", class: "btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_summary_list.html.erb
<div class='row'>
<table>
<% @user.summaries.each do |summary| %>
	<tr ><td>&nbsp;</td><td>&nbsp;</td></tr>
        <tr><!--第一行-->
	  <td><%= summary.content %></td>
        </tr>
<% end %>
    </table>
</div>
<hr>

app/views/users/_work_list.html.erb
<div class='row'><table><% @user.works.each do |work| %>	<tr ><td>&nbsp;</td><td>&nbsp;</td></tr>        <tr><!--第一行-->	  <td><%= work.join_date %>&nbsp;~&nbsp;<%= work.leave_date %></td>	  <td style='padding-left:30px'><%= work.employer %>&nbsp;|&nbsp;<%= work.industry %></td>        </tr>	<tr><!--第二行-->          <td></td>	  <td style='padding-left:30px'><%= work.title %></td>  </tr>	<tr><!--第三行-->	  <td class='pull-right'>岗位职责</td>	  <td style='padding-left:30px'><%=work.job_scope %></td>        </tr>	<tr style='border-bottom: 1px solid #eeeeee'><td>&nbsp;</td><td>&nbsp;</td></tr><% end %>    </table></div>

app/views/users/edit.html.erb
<div class= 'container'>
  <div class='well col-lg-7' style='margin-top:80px'>
	  <%= render 'form' %>
  </div>
</div>

app/views/users/editsalary.js.erb
$('#salary-content').html("<%= escape_javascript(render "salary_edit") %>");

app/views/users/hr.html.erb
<div class='container' style = 'margin-top:70px' >
  <!--标题行/头像-->
  <div class='well col-lg-7'>
    <p id="notice"><%= notice %></p><!--注册好返回这里有一条提示-->
    <div class = 'row'>
        <div class='col-lg-12'>
          			<%= @user.user_name.present? ? "#{@user.user_name} | " : "佚名 | " %>
          			<%= @user.city.present? ? "#{@user.city} | ": "全国 | " %>
          			<%= @user.title.present? ? " #{@user.title} | " : '找工作中 | ' %>
				        <%= remove_unwanted_words distance_of_time_in_words(Date.today,@user.birthday) unless @user.birthday == nil %>&nbsp;<!--注意I18n翻译的过程会出错，需要在cn.yml里设置-->
          		<!--avatar的size设置必须要这样，用@user.avatar.url(:small)不管用--> 
          		<%= image_tag(@user.avatar.url,size: '50x50', class: "img-circle") %>
          	    <% if @user.educations.first != nil %>
          	      <%= @user.educations.first.school %><%= @user.educations.first.degree %>&nbsp;|
              	<% end %>
		<% if @user.works.size >=1 %>                  
          	      <!--随机产生全部工作单位，index并不是works的id,是一个iteration的计数器,注意do里面要加index的对应-u -->
		      <% @user.works.shuffle.each_with_index do |f,u| %>
            	      <%= f.employer %><!--自动加一个空格-->
                    <%= "|" unless u == @user.works.size-1 %> <!--最后一次不加|-->                 
                  <% end %>
                <% else %>
                  工作单位保密&nbsp;
                <% end %>
        </div><!--col-lg-6-->
    </div><!--end row-->

  <div style='margin-top:20px' class='row'>
    <div class='col-lg-12'>
  	<table>
		<tr>
			<td style='padding-right:5px'><%= link_to '推荐',user_refer_path, class: 'btn-orange' %></td>
	    		<td style='padding-right:5px'><%= link_to '关注',user_refer_path, method: :get, class: 'btn-orange' %></td>
	    		<td style='padding-right:5px'><%= link_to '面试',user_refer_path, method: :get, class: 'btn-orange' %></td>
		<tr>
       </table>
    </div>
  </div>
  
  <div class='row'>
    <div class='col-lg-8'>
      <h4 style="color:#007722">自我介绍· · · · · ·</h4>
      <% if @user.summaries != nil %>
      <% @user.summaries.each do |f| %>
      	<div class='col-lg-12'>
      		<%= f.content %>
      	</div>
      <% end %>
      <% end %>
    </div><!--col-->

    <!-- 评价-->
    <div class='col-lg-4'>
      <table>
	<tr>
		<td>第一轮成功率&nbsp;</td>
		<td><% (((@total_apply_num.to_f-@fail_num.to_f)/(@total_apply_num >0 ? @total_apply_num.to_f : 1))*5).to_i.times do |f| %>    
      	<span style="margin-left:-3px;border-radius:1px;background-color:#ff632f;color:#ffffff;" class="glyphicon glyphicon-star" aria-hidden="true"></span>
<% end %></td>
	</tr>
        <tr>
		<td>评价</td>
		<td><% 5.times do |f| %>
      	  		<% if f<@user.reviews.average(:rating).to_i %>
				<span style="margin-left:-3px;border-radius:1px;background-color:#ff632f;color:#ffffff;" class="glyphicon glyphicon-star" aria-hidden="true"></span>
			<% else %>
				<span style="margin-left:-3px;border-radius:1px;background-color:#bbbbbb;color:#ffffff;" class="glyphicon glyphicon-star" aria-hidden="true"></span>
			<% end %>

  <% end %></td>
	</tr>
      </table>
    </div>
  </div>
  
  <div class='row'>
    <div class='col-lg-5'>
      <h4 style='color:#007722'>教育经历· · · · · ·</h4>
      <% if @user.educations != nil %>
      <% @user.educations.each do |f| %>
      <div class='col-lg-7'>
    	  <%= f.enter_school.strftime("%b %Y") %> - 
    	  <%= f.uptonow ? "现在" : f.leave_school.strftime("%b %Y") %>
      </div>
    	<div class='col-lg-5'>
    	  <table>
    	    <tr><td><%= f.school %></td></tr>
    	    <tr><td><%= f.major %> | <%= f.degree %></td></tr>
        </table> 
      </div>
        <% end %>
      <% end %>
    </div>
  </div><!--end row-->

  <div class='row'>
    <div id="accordion" role="tablist" aria-multiselectable="true">
      <div class='col-lg-8 list'>
        <%= link_to "#{@user.reviews.count}条评论" %>
      </div>
      <div class='col-lg-4 list'>
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <% if current_user != nil and @user.reviews.find_by(author_id: current_user.id)  %>
          		    <span id='label-4'>修改对他的评价</span>
                          <% else %>
            		  <span id='label-3'>我来评价他</span>
                <% end %>

        </a>
      </div>
    </div>
  </div><!--row-->

  <div class='row'>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne" style="margin:0px;">
      <div class='col-lg-6'>
        <div class="panel-body">
            <%= form_for([@user,@review]) do |f| %>
              <div class='col-lg-7'>
                <%= f.text_area :body,cols: 60, rows: 4, class: "form-control" %>
		          
		            <table>
                  <tr>
                    <td><%= f.label :你们共同的雇主 %></td>
                    <td><%= f.label :置顶, class: "pull-right"%><%= f.check_box :top %></td>
                  </tr>
                  <tr>
                    <td class='review'><%= f.select :employer,@user.works.collect { |p| [ p.employer ] } %></td>
                  </tr>
                </table>
              </div>

              <div class='col-lg-5'>
		<table>
		  <tr><td ><%= f.radio_button :rating,1 %>&nbsp;<span style='background-color:#ff632f;color:#ffffff' class="glyphicon glyphicon-star" aria-hidden="true"></span></td></tr>
		  <tr><td><%= f.radio_button :rating,2 %>&nbsp;<span style='background-color:#ff632f;color:#ffffff' class="glyphicon glyphicon-star" aria-hidden="true"></span><span style='background-color:#ff632f;color:#ffffff' class="glyphicon glyphicon-star" aria-hidden="true"></span></td></tr>
		  <tr><td><%= f.radio_button :rating,3 %>&nbsp;<span style='background-color:#ff632f;color:#ffffff' class="glyphicon glyphicon-star" aria-hidden="true"></span><span style='background-color:#ff632f;color:#ffffff' class="glyphicon glyphicon-star" aria-hidden="true"></span><span style="background-color:#ff632f;color:#ffffff" class="glyphicon glyphicon-star" aria-hidden="true"></span></td></tr>
		  <tr><td><%= f.radio_button :rating,4 %>&nbsp;<span style="background-color:#ff632f;color:#ffffff" class="glyphicon glyphicon-star" aria-hidden="true"></span><span style="background-color:#ff632f;color:#ffffff" class="glyphicon glyphicon-star" aria-hidden="true"></span><span style="background-color:#ff632f;color:#ffffff" class="glyphicon glyphicon-star" aria-hidden="true"></span><span style='background-color:#ff632f;color:#ffffff' class="glyphicon glyphicon-star" aria-hidden="true"></span></td></tr>
		  <tr><td><%= f.radio_button :rating,5 %>&nbsp;<span style="background-color:#ff632f;color:#ffffff" class="glyphicon glyphicon-star" aria-hidden="true"></span><span style="background-color:#ff632f;color:#ffffff" class="glyphicon glyphicon-star" aria-hidden="true"></span><span style="background-color:#ff632f;color:#ffffff" class="glyphicon glyphicon-star" aria-hidden="true"></span><span style="background-color:#ff632f;color:#ffffff" class="glyphicon glyphicon-star" aria-hidden="true"></span><span style="background-color:#ff632f;color:#ffffff" class="glyphicon glyphicon-star" aria-hidden="true"></span></td></tr>
		  <tr style='height:40px'><td><%= f.submit '发表', class: "btn btn-success btn-xs" %></td></tr>
	        </table>
	      </div><!--end col-lg-5-->
  	        <% end %> <!-- end form_for-->
        </div>
      </div>
    </div>
  </div> <!--end row -->

  <div id='content' class='col-lg-12'>
    <%= render(partial:'review')%> <!--这句话是从views/users/下面取模板对比views/jobs/show.html.erb-->
  </div>

</div><!--end well-->
</div><!--end container-->

app/views/users/index.html.erb
<div class = 'container' style='margin-top:80px'>
  <div class='well col-lg-6'>
  	<div class='row'>
	    <div class='col-lg-9'>
	      <h3>合适的候选人</h3>
	      <p>显示&nbsp;<%= @users.size %>位候选人</p>
	    </div>
	    <div class='col-lg-3'>
	      <%= paginate @users %>
	    </div>
    </div>
  
  <% @users.each do |user| %>
  <div class='row'>
	  <div class='col-lg-12' style='padding-top:16px'>
	    <table>
	      <tr >
				<td style = "vertical-align: top"> <!-- vertical-align用在table的td里可以顶部对齐，html经典书286页-->
				  <%= link_to image_tag(user.avatar.url, size: '95x95',class: 'avatar-index'),user_path(user), target: "_blank" %>
				</td>
				<td style = 'padding-left:15px'>
				      <p>
				      <%= link_to "#{user.user_name}",user_path(user),style: "font-size:18px;color:#1db0ed", target:"_blank" %>
					  </p>
					  <p style='font-family:Arial,"Microsoft YaHei", "微软雅黑"'>
					    <%= user.title %>
					  </p>
					  <p style='color: #a0a0a0;'>
					    <% collection = user.summaries.pluck(:content) %>
					    <%= truncate(collection.join(),length:150) %>&nbsp;
					    <%= link_to "详细内容",user_path(user),class: "xiangxi",style: 'color:#3b5893',target:"_blank" %>
				    <%=  %></p>
			    </td>
	       </tr>
	       <tr style='border-bottom: 1px solid #eeeeee;'>
				 <td>
				 </td>
				 <td style = 'font-family:Arial,"Microsoft YaHei", "微软雅黑";padding-left:15px;padding-bottom:20px'>
						 <%= user.city %>&nbsp;|
						 <% @sum = 0 %>
						 <% user.works.each do |f| %>
							 <% if f.leave_date != nil and f.join_date != nil %>
								 <% @sum += (remove_unwanted_words distance_of_time_in_words(f.leave_date, f.join_date)).to_i %>
							 <% end %>
					   	<% end %>
						<%= @sum %><span style='font-size: 10px'>年经验</span>&nbsp;|
						<%= number_with_precision(user.reviews.average(:rating), precision:1) %>&nbsp;
						<% user.reviews.average(:rating).to_i.times do |f|  %>
						  <span style="font-size:10px;color: #fcb82b;margin-left:-5px" class="glyphicon glyphicon-star" aria-hidden="true"></span>
						   <% end %>
						   &nbsp;|
						<%= number_with_precision((@sum.to_f/user.works.size unless user.works.size == 0), precision:1) %><span style='font-size: 10px'>年平均在职时间</span>&nbsp;|
						<% @total_apply_num = LineItem.where(talent_id: user.id).size %>
						<% @fail_num = LineItem.where(talent_id: user.id).where(status: "HR拒绝").size %>
						<% if @total_apply_num != 0 %>
						  <%= number_to_percentage(
						  	(number_with_precision(
						  		  (@total_apply_num.to_f-@fail_num.to_f)/@total_apply_num,precision:2
						  		  ).to_f*100),precision:0 
						  	  ) %>						  	
						<span style='font-size: 10px'>应聘成功率</span>&nbsp;|
						<% end %>
						<%= user.base_salary %><span style='font-size: 10px'>基本月薪</span>
				</td>
	      </tr>
	    </table>
	  </div>
  </div>
  <% end %>

  <div class='row'>
    <div class='col-lg-5'>

    </div>
    <div class='col-lg-2'>
      <%= paginate @users %>
    </div>
  </div>
  </div>
</div><!--container-->

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/refer.html.erb
<div class='container' style='padding-top:80px'>
	<div class='col-lg-3' style='padding-right:0px'>
		<div class='well' style='margin-bottom:5px'>
		  <div class='row'>
			  <div class='col-lg-4'>
				  <!--头像-->
				  <%= image_tag(@user.avatar.url,size:'70x70',class: 'avatar-refer-talent' ) %>
			    <% @user.reviews.average(:rating).to_i.times do |f|  %>
			      <span style="color: #fcb82b;" class="glyphicon glyphicon-star" aria-hidden="true"></span>
			    <% end %>

			  </div>
		          <div class='col-lg-8' >
				  <p style='color:#1db0ed;margin-bottom:0px'><%= @user.user_name %></p>
				  <p style='margin-bottom:0px'><%= @user.title %> &nbsp;<%= @user.city %></p>
				  <p style='font-size:12px;padding:0px'>
				  <% if @user.works != nil %>
           				<% @user.works.first(3).each do |f| %>
    	     				<% if f != @user.works.last %>
	       				<%= f.employer %> | <!-- |不能放在<% %>里-->
      	     				<% else %>
	       				<%= f.employer %>
             				<% end %>
           				<% end %>
					<% end %>
				  </p>

			  </div>
		  </div>

		  <div class='row'>
			  <div class ='col-lg-12'>
			  </div>
			  <div class ='col-lg-3'>
			    <p style='font-family:Arial,"Microsoft YaHei", "微软雅黑"'>经验</p>
			    <p><% @sum = 0 %>
			       <% @user.works.each do |f| %>
			       <% @sum += (remove_unwanted_words distance_of_time_in_words(f.leave_date, f.join_date)).to_i %>
			       <% end %>
			       <%= @sum %>
			       </p>
			  </div>
			  <div class ='col-lg-5'>
			    <p style='font-family:Arial,"Microsoft YaHei", "微软雅黑"'>平均在职时间</p>
		            <p><%= number_with_precision((@sum.to_f/@user.works.size unless @user.works.size == 0), precision:1) %>
		              </p>
		          </div>
			  <div class ='col-lg-4'>
			    <p style='font-family:Arial,"Microsoft YaHei", "微软雅黑"'>基本月薪</p>
			    <p><%= @user.base_salary %></p>
			  </div>
			  
		  </div><!--end row-->
	  </div><!-- end well-->
	  <div style='margin-top:0px'class='well'>
	    <h4 style='color:#1db0ed;font-size:18px'>工作经验</h4>	 
	    <hr>
            <% if @user.summaries != nil %>
            <% @user.summaries.each do |f| %>
		<p><%= f.content %></p>
    		<% end %>
	    <% end %>
	    <hr>
	    <h4 style='color:#1db0ed;font-size:18px'>教育经历</h4>
<% if @user.educations != nil %>
  <% @user.educations.each do |f| %>
    <table style='font-size:12px'>
      <tr>
	<td class="education" style='font-family:Arial,"Microsoft YaHei", "微软雅黑";font-size:12px'><%= f.enter_school.strftime("%b %Y") %> - 
	<%= f.leave_school.strftime("%b %Y") %></td>
<td class="education" style='font-family:Arial,"Microsoft YaHei", "微软雅黑";font-size:13px'>&nbsp;&nbsp;&nbsp;&nbsp;<%= f.school %></td>
      </tr>
      <tr>
	 <td class="education"></td>
         <td class="education" style='font-family:Arial,"Microsoft YaHei", "微软雅黑";font-size:12px'>&nbsp;&nbsp;&nbsp;&nbsp;<%= f.major %> | <%= f.degree %></td>
      </tr>
    </table>
    <% end %>
<% end %>
	    </div>
	</div>
  	
	<div class='col-lg-6' >
		<div class='list-group'>
			<a class="list-group-item">
			  <div><%= form_tag job_search_path,method: :get,remote:true do %><!--注意contrller转换到search_controller-->
			    <div class="input-group col-sm-9" style='margin:auto'><!--搜索框居中-->
          		      <%= text_field_tag :query,nil, class: 'form-control input-sm',placeholder:'搜索适合他/她的职位'  %>
			      <span class='input-group-btn'><%= submit_tag "搜索", name:nil, class: 'btn btn-info btn-sm' %></span><!--通过job_search.js.erb实现render--> </div>
	  		    <% end %>
      			  </div>
			</a>
			<div id='job_list'>
		   	 <%= render 'search/job_list' %>	
  		        </div><!-- job_list-->
		</div><!--list-group-->
  	</div>

</div>

app/views/users/update.js.erb
$('#salary-content').html("<%= escape_javascript(render "users/salary_list") %>");