config/routes.rb
Rails.application.routes.draw do
  get 'about_us',to: "company#about_us"
  resources :inquiries
  get 'invest', to: "inquiries#invest"
  get 'ourjobs',to: "inquiries#ourjobs"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'job_search', to: "search#job_search"
  get 'search/search', as: :search
  
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :registrations => "registrations" } #新建registrations controller,为了能够注册后重定向到after_signup_path
  scope '(:locale)' do #:locale是插入语，放在path前面，代表了地址里面出现的:locale参数如(en,cn等),
    get 'my_line_items',to:'home#my_line_items'
    get 'my_talents',to:'home#my_talents'
    get 'my_jobs',to:'home#my_jobs'
    
    get 'users/:id/refer', to:'users#refer', as: :user_refer # 简历上点击推荐按钮
    
    devise_scope :user do
      get "sign_out", to: "devise/sessions#destroy"
      get "sign_in", to: "devise/sessions#new"
      get "sign_up", to: "registrations#new"
      end
    root 'front#show'
      
    resources :jobs do
      get 'apply' => :apply
      get 'accept' => 'line_items#accept', as: :accept
      resources :comments
      resources :line_items do
      end
      resources :build, controller: 'jobs/build'
    end
    resources :after_signup
    resources :users do
      get "editsalary", to: "users#editsalary"
      resources :summaries
      resources :educations
      resources :works
      resources :reviews do #因为需要params[:user_id],所以把路径包含resources :users
        member { post :rating }
	get 'reviews/edit' => :edit
      end
    end
  end # end scope '(:locale)'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.user_type == "人事" and user.verify == "hr"
	 can [:update,:read], [LineItem]
	 can [:read], [User,Job,Review,Comment]
       elsif user.user_type == "猎头"
         can [:read,:create,:update,:destroy], :all
       elsif user.user_type == "求职者"
	 can :read, [Job,Review,Comment,User]
       else
	 can :read, [Job,Comment]
	 can [:read,:create,:update,:destroy], [Inquiry] 
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/boss.rb
class Boss < ActiveRecord::Base
  belongs_to :job
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :job
  belongs_to :user
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :user
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :job
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :bosses, :dependent => :destroy
  has_many :subordinates, :dependent => :destroy
  has_many :experiences, :dependent => :destroy
  has_many :line_items
  has_many :comments
  belongs_to:user # 发布者
  has_many :users, through: :line_items
  accepts_nested_attributes_for :bosses,:subordinates,:line_items, :comments, allow_destroy: true
  accepts_nested_attributes_for :experiences,allow_destroy: true,reject_if: proc { |attributes| attributes[:skill].blank? }
  letsrate_rateable "job_rating"
  letsrate_rateable "feedback"
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :job
  STATUS = ["等待应聘","发送到line","Turndown","等待反馈","初面","最后面试","Reject","Offer","保证期","推荐成功"]
  letsrate_rateable "service"
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user

end

app/models/subordinate.rb
class Subordinate < ActiveRecord::Base
  belongs_to :job
end

app/models/summary.rb
class Summary < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  letsrate_rater
  has_many :summaries, :dependent => :destroy
  has_many :educations, :dependent => :destroy
  has_many :works,:dependent => :destroy
  has_many :reviews, :dependent => :destroy
  has_many :line_items

  has_many :jobs # 发布的职位

  accepts_nested_attributes_for :summaries, allow_destroy:true,reject_if: proc { |attributes| attributes['content'].blank? } 
  accepts_nested_attributes_for :educations, allow_destroy:true,reject_if: proc { |attributes| attributes['school'].blank? }
  accepts_nested_attributes_for :works, allow_destroy:true,reject_if: proc { |attributes| attributes['employer'].blank? }# proc的用法http://ruby-doc.org/core-2.1.1/Proc.html
  accepts_nested_attributes_for :line_items
  accepts_nested_attributes_for :reviews
  accepts_nested_attributes_for :jobs

  # avatar设置
  has_attached_file :avatar, :styles => {:medium => "100x100#", :small => "50x50#"}, :default_url => "missing.png"#路径直接对应/app/assets/images/*,不能加其他
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  DEGREE_TYPES = ['专科','专升本','本科','统招硕士','工程硕士','MBA', '博士']


end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout :determine_layout
  
  def my_talents
    @my_talents = User.where(bank_id: current_user.id)
    if params[:my_query].present?
      params[:my_query].split(/ /).each do |f|
        if f=~/大学/
	  @my_talents = @my_talents.joins(:educations).uniq.where('educations.school LIKE ?',"%#{f}%")
	elsif f=~/北京|上海|天津|深圳|重庆|哈尔滨|长春|沈阳|呼和浩特|石家庄|乌鲁木齐|兰州|西宁|西安|银川|郑州|济南|太原|合肥|武汉|长沙|南京|成都|贵阳|昆明|南宁|拉萨|杭州|南昌|广州|福州|台北|海口|香港|澳门|无锡|苏州/
	  @my_talents = @my_talents.where("city like ?",$&)
	elsif f=~/[0-9][0-9]/ or f=~/[0-9]/
    	  @my_talents = @my_talents.where('birthday <= ?',Date.today-$&.to_i.years)
	else
	  @my_talents = @my_talents.joins(:works,:summaries).uniq.where('true_name LIKE ? OR user_name LIKE ? OR summaries.content LIKE ? OR works.title LIKE ? OR works.job_scope LIKE ? OR users.title LIKE ?',"%#{f}%","%#{f}%","%#{f}%","%#{f}%","%#{f}%","%#{f}%") # 搜索自我介绍、每段经历的title、job_scope和现在的title
	end
       end
    # 不用添加 my_talents.js 行
    end
  end

  # 我推荐的候选人
  def my_line_items
    @my_line_items = current_user.line_items.where(user_id: current_user.id)
    if params[:my_query].present?
      params[:my_query].split(/ /).each do |f|
	@my_line_items = @my_line_items.where('name LIKE ? OR status LIKE ? OR title LIKE ?',"%#{f}%","%#{f}%","%#{f}%")
      end
    end
  end

  # 我发布的职位
  def my_jobs
    @my_jobs = current_user.jobs
    if params[:my_query].present?
      params[:my_query].split(/ /).each do |f|
	@my_jobs = @my_jobs.where('title LIKE ? OR employer LIKE ? OR status LIKE ?',"%#{f}%","%#{f}%","%#{f}%")
      end
    end
end
  private
  def determine_layout
    case action_name
    when "my_jobs"
  	"home_jobs"
    else 
	"home"
  end
  end
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/home/_my_jobs_list.html.erb
	  <table class='table table-hover'>
	    <thead style='color:#aaaaaa;font-size:12px;weight:bold'>
		    <th>职位名</th>
		    <th>公司</th>
	    	    <th>简历数</th>
		    <th>发送到line</th>
	    	    <th>初面</th>
		    <th>最后面试</th>
		    <th>赏金</th>
		    <th>备注</th>
	</thead>
	<% @my_jobs.order('created_at desc').each do |f| %>
		<tr>
			<td>
			  <%= f.title %>
			</td>
			<td>
			  <%= f.employer %>
			</td>
			<td>
				<%= link_to "#{f.line_items.size unless f.line_items == nil}",job_apply_path(job_id:f.id) %>
			</td>
			<td>
			  <%= f.line_items.where("status LIKE ? or status LIKE ? or status LIKE ?", "发送到line","初面","最后面试").size unless f.line_items == nil %>
		  	</td>
			<td>
				<%= f.line_items.where(status: "初面").size unless f.line_items == nil %>
			</td>
			<td>
				<%= f.line_items.where(status: "最后面试").size unless f.line_items == nil %>
			</td>
			<td>
				<%= f.commission %>
			</td>
			<td>
				<%= f.memo %>
			</td>
		</tr>
		<% end %>
	</table>
		    

app/views/home/_my_line_items_list.html.erb
	  <table class='table table-hover'>
	    <thead style='color:#aaaaaa;font-size:12px;weight:bold'>
		    <th></th>
		    <th>用户名</th>
		    <th>状态</th>
		    <th>职位</th>
		    <th>客户</th>
		    <th>联系人</th>
		    <th>推荐日期</th>
		    <th>反馈</th>
	  </thead>
	  <% @my_line_items.order('updated_at desc').each do |f| %>
	    <% if User.find_by id: f.talent_id %>
	      <% talent = User.find_by id: f.talent_id %>
	      <% job = Job.find_by id: f.job_id %>
	      <% hr = User.find_by id: job.user_id %> 
	    <tr>
	      <td width="30px">
		<% if talent.present? %>
		  <%= link_to image_tag(talent.avatar.url, size:'30x30',class: 'img-circle'),user_path(id:talent.id),target:"_blank" %>
	        <% end %>
	      </td>
	      <td>
		      <%= talent.present? ? (link_to "#{talent.user_name}",user_path(talent),method: :get,target: :_blank) : f.name %></td>
	      <td>
		      <%= f.status %>
	      </td>
	      <td>
		      <%= link_to "#{job.title}",job_path(job),target: :_blank %>
	      </td>
	      <td>
		      <%= job.employer %>
	      </td>
	      <td>
		      <%= link_to "#{hr.user_name}",user_path(hr), target: :_blank %>
	      </td>
	      <td>
		      <%= f.created_at.strftime("%y-%m-%d") %>
	      </td>
	      <td>
		      <%= f.comment %>
	      </td>
	    </tr>
            <% end %>
            <% end %>
    </table>

app/views/home/_my_talents_list.html.erb
	  <table class='table table-hover'>
	    <thead style='color:#aaaaaa;font-size:12px;weight:bold'>
		    <th></th>
		    <th>用户名</th>
		    <th>年龄</th>
		    <th>地点</th>
		    <th>当前雇主</th>
		    <th>职位</th>
		    <th>行业</th>
		    <th>备注</th>
	  </thead>
	  <% @my_talents.each do |f| %>
		  <tr>
	      <td width="30px">
		      <%= link_to image_tag(f.avatar.url, size:'30x30',class: 'img-circle'),user_path(id:f.id),target:"_blank" %>
	      </td>
  	      <td>
		  <%= f.user_name %>
	      </td>
	      <td>
		  <%= remove_unwanted_words distance_of_time_in_words(Date.today,f.birthday) unless f.birthday == nil %>
	      </td>
	      <td>
		      <%= f.city %>
	      </td>
	      <td>
		      <% if f.works.find_by(uptonow: true)  %> <!-- find_by可用作判断, where不用作判断-->
			<% work = f.works.where(uptonow: true).take %>
			<% else work = f.works.where(leave_date: f.works.maximum(:leave_date)).take %><!--加take可以用.employer-->
		      <% end %>
	    	      <%=  work.employer unless work==nil %>
	      </td>
	      <td>
		      <%= f.title %>
	      </td>
	      <td>
		      <%= work.industry %>
	      </td>
	      <td>
	  	  <%= f.reviews.find_by(author_id:current_user.id).body unless f.reviews.find_by(author_id:current_user) == nil %>
              </td>
	    </tr>
            <% end %>
    </table>

app/views/home/my_jobs.html.erb
<div class='col-lg-10'>
  <div style='margin-top:0px' class='row pull-right'>
  </div>
  <br>
  <br>
  <div class='row' id='my_jobs_list'>
	  <%= render 'my_jobs_list' %>
  </div>
</div>

app/views/home/my_line_items.html.erb
<div class='col-lg-10'>
  <div style='margin-top:0px' class='row pull-right'>
	  <%= form_tag my_line_items_path,method: :get,remote:true do %>
  	  <%= text_field_tag :my_query,nil, style:"height:30px",class: 'form-control' %><!--class至少要放到第三个参数-->
		<%= submit_tag "",style:'display:none'  %>
	<% end %>
  </div>
  <br>
  <br>
  <div class='row' id='my_line_items_list'>
	  <%= render 'my_line_items_list' %>
  </div>
</div>

app/views/home/my_line_items.js.erb
$('#my_line_items_list').html("<%= escape_javascript(render "home/my_line_items_list") %>");

app/views/home/my_talents.html.erb
<div class='col-lg-10'>
  <div class='row pull-right'>
	  <%= form_tag my_talents_path,method: :get,remote:true do %>
  	  <%= text_field_tag :my_query,nil, class: 'form-control' %><!--class至少要放到第三个参数-->
		<%= submit_tag "",style:'display:none'  %>
	<% end %>
  </div>
  <br>
  <br>
  <div class='row' id='my_talents_list'>
	  <%= render 'my_talents_list' %>
  </div>
</div>

app/views/home/my_talents.js.erb
$('#my_talents_list').html("<%= escape_javascript(render "home/my_talents_list") %>");